version: '3'

services:
  server:
    depends_on:
      - hacker_rank_db
    container_name: server
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /server/node_modules
      - .:/server
    environment:
      NODE_ENV: development
    command: ["yarn", "dev"]
    restart: always
    networks:
      - server-net

  hacker_rank_db:
    restart: always
    container_name: hacker_rank_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: strongPassword
      POSTGRES_DB: hacker_rank
    networks:
      - server-net
  
  adminer:
    restart: always
    image: adminer
    ports:
      - 4040:8080
    networks:
      - server-net

networks:
  server-net:
    driver: bridge
